export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const COURSES_FETCHED = 'COURSES_FETCHED';
export const COURSE_CREATED = 'COURSE_CREATED';
export const AUTHORS_FETCHED = 'AUTHORS_FETCHED';
export const AUTHOR_CHOSEN = 'AUTHOR_CHOSEN';